//----------------------------------------------------------------------------------------------
//
//	duplicate a bind geometry and deletes the intermediate shape node
//
//	SCRIPT:			icDuplicateSkin.mel
//
//	AUTHOR:			Ingo Clemens
//					bravestrabbit@gmx.de
//	DATE:			Jan 25, 2009
//					created: Jan 25, 2009
//
//----------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------
//
//	USE AND MODIFY AT YOUR OWN RISK!!
//
//----------------------------------------------------------------------------------------------


//----------------------------------------------------------------------------------------------
//
// checks if the selected object is bind to a skin cluster
//
//----------------------------------------------------------------------------------------------

global proc int icDSconfirmSkin ( string $sel )
{
	string $selShape[] = `listRelatives -s $sel`;
	string $inputs[] = `listConnections -s 1- d 0 $selShape[0]`;
	int $flag = 0;
	for ($i in $inputs)
	{
		if (`nodeType $i` == "skinCluster")
		{
			$flag = 1;
		}
	}
	return $flag;
}

//----------------------------------------------------------------------------------------------
//
// duplicates the bind geometry and deletes the intermediate shape node
//
//----------------------------------------------------------------------------------------------

global proc icDuplicateSkin ()
{
	string $sel[] = `ls -sl`;
	
	int $flag = icDSconfirmSkin ( $sel[0] );

	if ($flag == 1)
	{
		string $dup[] = `duplicate -rr -rc $sel`;
		string $shapes[] = `listRelatives -s $dup[0]`;
		for ($s in $shapes)
		{
			if (`getAttr ($s + ".intermediateObject")`)
			{
				delete $s;
			}
		}
		setAttr -l 0 ($dup[0] + ".tx");
		setAttr -l 0 ($dup[0] + ".ty");
		setAttr -l 0 ($dup[0] + ".tz");
		setAttr -l 0 ($dup[0] + ".rx");
		setAttr -l 0 ($dup[0] + ".ry");
		setAttr -l 0 ($dup[0] + ".rz");
		setAttr -l 0 ($dup[0] + ".sx");
		setAttr -l 0 ($dup[0] + ".sy");
		setAttr -l 0 ($dup[0] + ".sz");
	}
}
