global proc welcomeWindow()
{
	if ((`window -ex welcomeWin`)== true) deleteUI welcomeWin;
	window -t "Thinkgazer.com" -wh 270 100 -s 0  welcomeWin;
	menuBarLayout ;
		paneLayout;
	string $getName = `getenv USERNAME`;
	columnLayout -adj 1;
	text -l "Hi";
	text -l $getName -fn "boldLabelFont";
	image  -image   "F:/website/logo/Final_Thinkgazer_logo/Thinkgazer_Webiste_Logo.png" -w 254 -h 70;
	text -l "Welcome's U.";
	showWindow;

}
welcomeWindow;
NPautoSaveOptions();




